version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      - mynet

  spring-boot-app:
    image: spring-mwt
    build: .
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgresdb
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    networks:
        - mynet

networks:
  mynet:  # Define the existing network
    external: true  # Specify

